# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('handling_editor', 'Handling Editor'), ('managing_editor', 'Managing Editor'), ('editor_in_chief', 'Editor-in-Chief')], default='handling_editor', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('decision_type', models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject'), ('desk_reject', 'Desk Reject'), ('reject_resubmit', 'Reject — Invite Resubmission')], max_length=30)),
                ('letter', models.TextField(blank=True, default='')),
                ('priority_issues', models.TextField(blank=True, default='')),
                ('conflict_resolution_note', models.TextField(blank=True, default='')),
                ('instructions_to_author', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_decisions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_decisions', to='submissions.submission')),
            ],
            options={
                'ordering': ['-round'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_ok', models.BooleanField(default=False)),
                ('scope_fit_ok', models.BooleanField(default=False)),
                ('ethics_ok', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('identity_leakage_risk', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('result', models.CharField(blank=True, choices=[('pass_to_desk', 'Pass to Desk Review'), ('return_to_author', 'Return to Author for Corrections'), ('reject', 'Reject')], max_length=30)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_checks', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_checks', to='submissions.submission')),
            ],
        ),
    ]
