# Generated by Django 5.1.4 on 2026-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialassignment',
            name='role',
            field=models.CharField(choices=[('handling_editor', 'Handling Editor'), ('associate_editor', 'Associate Editor'), ('guest_editor', 'Guest Editor'), ('managing_editor', 'Managing Editor'), ('editor_in_chief', 'Editor-in-Chief')], default='handling_editor', max_length=30),
        ),
    ]
