# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOIDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposited', 'Deposited'), ('registered', 'Registered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('crossref_response', models.JSONField(blank=True, default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doi_deposit', to='documents.canonicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='HTMLBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('build_hash', models.CharField(blank=True, max_length=64)),
                ('html_content', models.TextField(blank=True, default='')),
                ('table_of_contents', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('access_mode', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered Users'), ('embargoed', 'Embargoed')], default='open', max_length=20)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_build', to='documents.canonicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='PDFExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('flat', 'Flat'), ('interactive', 'Interactive')], default='flat', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_exports/')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_exports', to='documents.canonicaldocument')),
            ],
        ),
    ]
