# Generated by Django 5.1.4 on 2026-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfexport',
            name='mode',
            field=models.CharField(choices=[('flat', 'Flat')], default='flat', max_length=20),
        ),
    ]
