# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('article_type', models.CharField(choices=[('research_article', 'Research Article'), ('critical_essay', 'Critical Essay'), ('reflective_paper', 'Reflective Paper'), ('hybrid_media', 'Hybrid Media Contribution'), ('editorial', 'Editorial'), ('book_review', 'Book Review'), ('practice_documentation', 'Practice Documentation')], default='research_article', max_length=50)),
                ('abstract', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('artistic_mediums', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted – Awaiting Technical Check'), ('technical_check', 'Technical Check'), ('desk_review', 'Desk Review'), ('reviewer_suggestion', 'Reviewer Suggestion'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('in_production', 'In Production'), ('published', 'Published'), ('rejected', 'Rejected'), ('desk_rejected', 'Desk Rejected')], default='draft', max_length=30)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('funding_statement', models.TextField(blank=True, default='')),
                ('conflict_of_interest', models.TextField(blank=True, default='None declared.')),
                ('ethics_declaration', models.JSONField(blank=True, default=dict)),
                ('ai_use_statement', models.TextField(blank=True, default='')),
                ('license_preference', models.CharField(default='CC-BY', max_length=50)),
                ('originality_confirmed', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('corresponding_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_submissions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='journal.issue')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('manuscript_file', models.FileField(upload_to='manuscripts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('response_letter', models.FileField(blank=True, null=True, upload_to='response_letters/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='submissions.submission')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('submission', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('data', 'Dataset / Appendix'), ('supplementary', 'Supplementary File'), ('transcript', 'Transcript'), ('poster', 'Video Poster Image')], max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('original_filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True, default='')),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('rights_cleared', models.BooleanField(default=False)),
                ('rights_notes', models.TextField(blank=True, default='')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='submissions.submissionrevision')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, default='')),
                ('provider_submission_id', models.CharField(blank=True, max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_check', to='submissions.submissionrevision')),
            ],
        ),
    ]
