# Generated by Django 5.1.4 on 2026-05-15 20:25

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalconfig_legal_notice'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['author'], name='submissions_author__272c77_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='submission_keywords_gin'),
        ),
    ]
