# Generated by Django 5.1.4 on 2026-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_keywords_gin_index_and_status_author_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionrevision',
            name='source_type',
            field=models.CharField(choices=[('latex', 'LaTeX'), ('wysiwyg', 'WYSIWYG Editor')], default='latex', max_length=16),
        ),
        migrations.AddField(
            model_name='submissionrevision',
            name='wysiwyg_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionrevision',
            name='manuscript_file',
            field=models.FileField(blank=True, null=True, upload_to='manuscripts/'),
        ),
    ]
