# Generated by Django 5.1.4 on 2026-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_wysiwyg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cover_caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image shown at the top of the article page (falls back to the issue cover image)', null=True, upload_to='covers/'),
        ),
    ]
