# Generated by Django 5.1.4 on 2026-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_cover_caption_submission_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cover_derivatives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='derivatives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='intrinsic_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='intrinsic_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='role',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image shown at the top of the article page (falls back to the issue cover image). Recommended 1920×1080 (16:9), up to 2500px wide.', null=True, upload_to='covers/'),
        ),
    ]
