# Generated by Django 5.1.4 on 2026-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_cover_derivatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionasset',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='hls_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='hls_master',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submissionasset',
            name='hls_status',
            field=models.CharField(choices=[('none', 'Not applicable'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='none', max_length=12),
        ),
    ]
