# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('parse_warnings', models.JSONField(blank=True, default=list)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('html_build_ok', models.BooleanField(default=False)),
                ('pdf_build_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_document', to='submissions.submissionrevision')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('rights', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_assets', to='documents.canonicaldocument')),
                ('submission_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.submissionasset')),
            ],
        ),
    ]
