# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('editorial_note', models.TextField(blank=True, default='')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('call_for_submissions', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-year', '-number'],
            },
        ),
        migrations.CreateModel(
            name='JournalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trans/Act', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('issn_print', models.CharField(blank=True, default='', max_length=20)),
                ('issn_online', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('editorial_email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('review_model', models.CharField(choices=[('double_blind', 'Double Blind'), ('single_blind', 'Single Blind'), ('open', 'Open Review'), ('editorial', 'Editorial Review')], default='double_blind', max_length=30)),
                ('submission_open', models.BooleanField(default=True)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('imprint', models.TextField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('footer_partners', models.TextField(blank=True, default='')),
                ('submission_guidelines', models.TextField(blank=True, default='')),
                ('about_text', models.TextField(blank=True, default='')),
                ('mission_text', models.TextField(blank=True, default='')),
                ('methodology_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Configuration',
                'verbose_name_plural': 'Journal Configuration',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='journal.issue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
