# Generated by Django 5.1.4 on 2026-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalconfig_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='email_backend_type',
            field=models.CharField(choices=[('mailersend', 'MailerSend (API)'), ('smtp', 'SMTP')], default='mailersend', max_length=20),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
