# Generated by Django 5.1.4 on 2026-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalconfig_smtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='legal_notice',
            field=models.TextField(blank=True, default='', help_text='Optional jurisdiction-specific text appended to the Terms & Conditions page (DPO contact, supervisory authority, etc.)'),
        ),
    ]
