# Generated by Django 5.1.4 on 2026-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalconfig_legal_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
