# Generated by Django 5.1.4 on 2026-06-10 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_footer_text'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='contribute_caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='contribute_image',
            field=models.ImageField(blank=True, help_text='Image shown in the "Contribute" section of the homepage', null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='contribute_text',
            field=models.TextField(blank=True, default='', help_text='Text of the "Contribute" section on the homepage'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='featured_rotation_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='How long a homepage "Across the archive" selection stays before rotating (months)'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='home_hero_caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='home_hero_image',
            field=models.ImageField(blank=True, help_text='Large image shown top-right on the homepage (falls back to the current issue cover)', null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='news_text',
            field=models.TextField(blank=True, default='', help_text='Content of the public News page'),
        ),
        migrations.AlterField(
            model_name='journalconfig',
            name='name',
            field=models.CharField(default='IN/ACT', max_length=255),
        ),
        migrations.CreateModel(
            name='FeaturedSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='auto', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='featured_in', to='production.htmlbuild')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
