# Generated by Django 5.1.4 on 2026-06-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journalconfig_contribute_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='show_archive_section',
            field=models.BooleanField(default=True, help_text='Show the "Across the archive" section on the homepage'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='show_contribute_section',
            field=models.BooleanField(default=True, help_text='Show the "Contribute" section on the homepage'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='show_filtered_section',
            field=models.BooleanField(default=True, help_text='Show the keyword/year filtered articles section on the homepage'),
        ),
        migrations.AlterField(
            model_name='journalconfig',
            name='name',
            field=models.CharField(default='inAct', max_length=255),
        ),
    ]
