# Generated by Django 5.1.4 on 2026-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='policy_text',
            field=models.TextField(blank=True, default='', help_text='Content of the public Policy page (/policy/) — Open Access, ethics, data sharing, charges.'),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='terms_text',
            field=models.TextField(blank=True, default='', help_text='Content of the public Terms & Conditions page (/terms/). When blank, the built-in default text is shown.'),
        ),
    ]
