# Generated by Django 5.1.4 on 2026-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_seed_policy_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='editorial_board_text',
            field=models.TextField(blank=True, default='', help_text='Intro text shown above the members on the Editorial Board page (/editorial-board/).'),
        ),
    ]
