# Generated by Django 5.1.4 on 2026-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journalconfig_editorial_board_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='faq_text',
            field=models.TextField(blank=True, default='', help_text='Content of the public FAQ page (/faq/).'),
        ),
    ]
