# Generated by Django 5.1.4 on 2026-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_set_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalconfig',
            name='name',
            field=models.CharField(default='inACT', max_length=255),
        ),
    ]
