# Generated by Django 5.1.4 on 2026-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_newspost_featured_image_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Shown as the card thumbnail and as the hero image at the top of the detail page.', null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Rich-text teaser shown on the news card (WYSIWYG). Falls back to the start of the body.'),
        ),
    ]
