# Generated by Django 5.1.4 on 2026-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_newspost_summary_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text='e.g. country or faculty, shown under the name', max_length=255)),
                ('url', models.URLField(blank=True, default='', help_text='Official website (opens in a new tab)')),
                ('logo', models.FileField(blank=True, null=True, upload_to='partners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
