# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('magic_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_invitations', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_invitations', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_keywords', models.JSONField(blank=True, default=list)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('sub_disciplines', models.JSONField(blank=True, default=list)),
                ('methodologies', models.JSONField(blank=True, default=list)),
                ('artistic_mediums', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('preferred_review_models', models.JSONField(blank=True, default=list)),
                ('expertise_statement', models.TextField(blank=True, default='')),
                ('avg_turnaround_days', models.FloatField(default=21.0)),
                ('responsiveness_score', models.FloatField(default=0.7)),
                ('quality_score', models.FloatField(default=0.7)),
                ('active_invitations_count', models.PositiveIntegerField(default=0)),
                ('total_reviews_completed', models.PositiveIntegerField(default=0)),
                ('last_invited_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved by Editor'), ('rejected', 'Rejected by Editor'), ('invited', 'Invitation Sent')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_suggestions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_suggestions', to='submissions.submission')),
                ('suggested_by_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_suggestions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
