# Generated by Django 5.1.4 on 2026-04-09 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('moderation_required', 'Moderation Required'), ('moderated', 'Moderated'), ('released', 'Released to Author')], default='draft', max_length=30)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('expertise_self_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('major_issues', models.TextField(blank=True, default='')),
                ('minor_issues', models.TextField(blank=True, default='')),
                ('ethical_concerns', models.TextField(blank=True, default='')),
                ('comments_to_author', models.TextField(blank=True, default='')),
                ('comments_to_editor', models.TextField(blank=True, default='')),
                ('conflict_confirmed', models.BooleanField(default=False)),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviewers.reviewerinvitation')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.CharField(blank=True, max_length=100)),
                ('block_id', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('selector_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_comments_to_author', models.TextField(blank=True, default='')),
                ('moderated_comments_to_author', models.TextField(blank=True, default='')),
                ('moderation_notes', models.TextField(blank=True, default='')),
                ('conflict_flagged', models.BooleanField(default=False)),
                ('conflict_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_moderation', 'In Moderation'), ('moderated', 'Moderated'), ('released', 'Released to Author')], default='submitted', max_length=20)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_moderations', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='reviews.review')),
            ],
        ),
    ]
