# Generated by Django 5.1.4 on 2026-05-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewannotation_released_to_author'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='submissions.submissionrevision'),
        ),
    ]
