# Generated by Django 5.1.4 on 2026-07-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('accept', 'Accept without revisions'), ('minor_revision', 'Accept with minor revisions'), ('major_revision', 'Revise and resubmit'), ('reject', 'Reject')], max_length=20),
        ),
    ]
