# Generated by Django 5.1.4 on 2026-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submission_received', 'Submission Received'), ('corrections_requested', 'Corrections Requested'), ('reviewer_invited', 'Reviewer Invited'), ('reviewer_accepted', 'Reviewer Accepted'), ('reviewer_declined', 'Reviewer Declined'), ('review_submitted', 'Review Submitted'), ('review_released', 'Review Released to Author'), ('review_overdue', 'Review Overdue'), ('under_review', 'Submission Under Review'), ('decision_sent', 'Decision Sent'), ('proof_ready', 'Proof Ready'), ('published', 'Article Published'), ('issue_published', 'Issue Published'), ('returned_to_author', 'Returned for Correction'), ('revision_submitted', 'Revision Submitted'), ('general', 'General')], default='general', max_length=40),
        ),
    ]
